### ISSUE TITLE
Download Data to an Excel File Feature

### ISSUE THREAD

**Issue by zsmith10** [cmciosu/hemp-db#3]
Statement:
As a student researcher, I want to download an Excel file that contains all of the relevant data that I have selected from the database. I want the Excel file to have the correct amount of rows and columns along with the correct data that I selected. 

Background:
This feature will be important for the researchers to be able to download the data easily so that they can perform analysis on the data. It is essential that the data in the Excel file is correct so that the researchers do not have to take more time to fix the Excel sheet.

Requirements:
The user must be given the option to select the data that they want to download, and the application must convert the selected data into an Excel sheet and save it to the user's file system. 

Dependencies: 
Blocked By:
UI Implementation
Database Implementation
   -CRUD Implementation
Admin Approval Implementation

Definition of Done:
A fully implemented feature that allows the user to download selected data into an Excel sheet. The feature passes tests for edge cases that might cause the Excel file to download incorrectly. The feature along with how to use it will be written into the documentation.

**Comment by paullpp** [comment]
dump feature - select * -> export

**Comment by paullpp** [comment]
done for csv
