### ISSUE TITLE
Complex query criteria 

### ISSUE THREAD

**Issue by meithofdOSU** [cmciosu/hemp-db#4]
Statement: 

As a research student, my job is to collect data for making policy changes regarding the Hemp Industries. I am interested in analyzing the data based on specific criteria queries to notice trends, gain insight, prediction, optimization, and understanding data patterns.

Background: 

This feature will require a back-end database to have basic C.R.U.D commands for the database to be able to query the data meeting the criteria of the users. The data needed to do this action is already provided from the project partner’s previous method of data storage.
Requirements:
-Web Browser 
-Client/server API
-Database (Python, MySQL, DBMongo, …) with software Implemented C.R.U.D command.
-Take existing data from the Excel spreadsheet and import it into the database.
 
Dependencies:
-Front-End \ Back-End 
- DBMS
-Programming Language framework (Django, Nodejs………..)
-basic data manipulation of C.R.U.D
 
Definition of done
An implementation of a database that lets users perform complex queries with diverse criteria to meet their requirements. Also, it will be implemented for resilient, reliable, highly efficient data transactions in handling a high volume of data.

**Comment by paullpp** [comment]
feedback:
put this in data viz layer, keep UI for data entry only
